// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: fileasset_backend_api/download/v1/download.proto

package downloadv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on FetchUrlRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *FetchUrlRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FetchUrlRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FetchUrlRequestMultiError, or nil if none found.
func (m *FetchUrlRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *FetchUrlRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetProject()) > 100 {
		err := FetchUrlRequestValidationError{
			field:  "Project",
			reason: "value length must be at most 100 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetUid() < 0 {
		err := FetchUrlRequestValidationError{
			field:  "Uid",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetModule()) > 100 {
		err := FetchUrlRequestValidationError{
			field:  "Module",
			reason: "value length must be at most 100 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 30 || l > 50 {
		err := FetchUrlRequestValidationError{
			field:  "Name",
			reason: "value length must be between 30 and 50 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetTtl(); val <= 0 || val >= 604800 {
		err := FetchUrlRequestValidationError{
			field:  "Ttl",
			reason: "value must be inside range (0, 604800)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetCount() < 0 {
		err := FetchUrlRequestValidationError{
			field:  "Count",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return FetchUrlRequestMultiError(errors)
	}

	return nil
}

// FetchUrlRequestMultiError is an error wrapping multiple validation errors
// returned by FetchUrlRequest.ValidateAll() if the designated constraints
// aren't met.
type FetchUrlRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FetchUrlRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FetchUrlRequestMultiError) AllErrors() []error { return m }

// FetchUrlRequestValidationError is the validation error returned by
// FetchUrlRequest.Validate if the designated constraints aren't met.
type FetchUrlRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FetchUrlRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FetchUrlRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FetchUrlRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FetchUrlRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FetchUrlRequestValidationError) ErrorName() string { return "FetchUrlRequestValidationError" }

// Error satisfies the builtin error interface
func (e FetchUrlRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFetchUrlRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FetchUrlRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FetchUrlRequestValidationError{}

// Validate checks the field values on FetchUrlResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *FetchUrlResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FetchUrlResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FetchUrlResponseMultiError, or nil if none found.
func (m *FetchUrlResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *FetchUrlResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Url

	if len(errors) > 0 {
		return FetchUrlResponseMultiError(errors)
	}

	return nil
}

// FetchUrlResponseMultiError is an error wrapping multiple validation errors
// returned by FetchUrlResponse.ValidateAll() if the designated constraints
// aren't met.
type FetchUrlResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FetchUrlResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FetchUrlResponseMultiError) AllErrors() []error { return m }

// FetchUrlResponseValidationError is the validation error returned by
// FetchUrlResponse.Validate if the designated constraints aren't met.
type FetchUrlResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FetchUrlResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FetchUrlResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FetchUrlResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FetchUrlResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FetchUrlResponseValidationError) ErrorName() string { return "FetchUrlResponseValidationError" }

// Error satisfies the builtin error interface
func (e FetchUrlResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFetchUrlResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FetchUrlResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FetchUrlResponseValidationError{}
