// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: fileasset_queue_api/queue/v1/queue.proto

package queuev1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ConnectRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ConnectRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConnectRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ConnectRequestMultiError,
// or nil if none found.
func (m *ConnectRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ConnectRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return ConnectRequestMultiError(errors)
	}

	return nil
}

// ConnectRequestMultiError is an error wrapping multiple validation errors
// returned by ConnectRequest.ValidateAll() if the designated constraints
// aren't met.
type ConnectRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConnectRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConnectRequestMultiError) AllErrors() []error { return m }

// ConnectRequestValidationError is the validation error returned by
// ConnectRequest.Validate if the designated constraints aren't met.
type ConnectRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConnectRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConnectRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConnectRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConnectRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConnectRequestValidationError) ErrorName() string { return "ConnectRequestValidationError" }

// Error satisfies the builtin error interface
func (e ConnectRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConnectRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConnectRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConnectRequestValidationError{}

// Validate checks the field values on ConnectResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ConnectResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConnectResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ConnectResponseMultiError, or nil if none found.
func (m *ConnectResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ConnectResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Status

	if len(errors) > 0 {
		return ConnectResponseMultiError(errors)
	}

	return nil
}

// ConnectResponseMultiError is an error wrapping multiple validation errors
// returned by ConnectResponse.ValidateAll() if the designated constraints
// aren't met.
type ConnectResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConnectResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConnectResponseMultiError) AllErrors() []error { return m }

// ConnectResponseValidationError is the validation error returned by
// ConnectResponse.Validate if the designated constraints aren't met.
type ConnectResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConnectResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConnectResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConnectResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConnectResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConnectResponseValidationError) ErrorName() string { return "ConnectResponseValidationError" }

// Error satisfies the builtin error interface
func (e ConnectResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConnectResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConnectResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConnectResponseValidationError{}

// Validate checks the field values on TaskRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TaskRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TaskRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TaskRequestMultiError, or
// nil if none found.
func (m *TaskRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TaskRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TaskId

	// no validation rules for Content

	if len(errors) > 0 {
		return TaskRequestMultiError(errors)
	}

	return nil
}

// TaskRequestMultiError is an error wrapping multiple validation errors
// returned by TaskRequest.ValidateAll() if the designated constraints aren't met.
type TaskRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TaskRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TaskRequestMultiError) AllErrors() []error { return m }

// TaskRequestValidationError is the validation error returned by
// TaskRequest.Validate if the designated constraints aren't met.
type TaskRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TaskRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TaskRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TaskRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TaskRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TaskRequestValidationError) ErrorName() string { return "TaskRequestValidationError" }

// Error satisfies the builtin error interface
func (e TaskRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTaskRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TaskRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TaskRequestValidationError{}

// Validate checks the field values on TaskResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TaskResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TaskResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TaskResponseMultiError, or
// nil if none found.
func (m *TaskResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *TaskResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TaskId

	// no validation rules for Status

	if len(errors) > 0 {
		return TaskResponseMultiError(errors)
	}

	return nil
}

// TaskResponseMultiError is an error wrapping multiple validation errors
// returned by TaskResponse.ValidateAll() if the designated constraints aren't met.
type TaskResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TaskResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TaskResponseMultiError) AllErrors() []error { return m }

// TaskResponseValidationError is the validation error returned by
// TaskResponse.Validate if the designated constraints aren't met.
type TaskResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TaskResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TaskResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TaskResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TaskResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TaskResponseValidationError) ErrorName() string { return "TaskResponseValidationError" }

// Error satisfies the builtin error interface
func (e TaskResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTaskResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TaskResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TaskResponseValidationError{}

// Validate checks the field values on TaskProgress with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TaskProgress) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TaskProgress with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TaskProgressMultiError, or
// nil if none found.
func (m *TaskProgress) ValidateAll() error {
	return m.validate(true)
}

func (m *TaskProgress) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TaskId

	// no validation rules for Progress

	if len(errors) > 0 {
		return TaskProgressMultiError(errors)
	}

	return nil
}

// TaskProgressMultiError is an error wrapping multiple validation errors
// returned by TaskProgress.ValidateAll() if the designated constraints aren't met.
type TaskProgressMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TaskProgressMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TaskProgressMultiError) AllErrors() []error { return m }

// TaskProgressValidationError is the validation error returned by
// TaskProgress.Validate if the designated constraints aren't met.
type TaskProgressValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TaskProgressValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TaskProgressValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TaskProgressValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TaskProgressValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TaskProgressValidationError) ErrorName() string { return "TaskProgressValidationError" }

// Error satisfies the builtin error interface
func (e TaskProgressValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTaskProgress.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TaskProgressValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TaskProgressValidationError{}

// Validate checks the field values on TaskResult with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TaskResult) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TaskResult with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TaskResultMultiError, or
// nil if none found.
func (m *TaskResult) ValidateAll() error {
	return m.validate(true)
}

func (m *TaskResult) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TaskId

	// no validation rules for Error

	// no validation rules for Content

	if len(errors) > 0 {
		return TaskResultMultiError(errors)
	}

	return nil
}

// TaskResultMultiError is an error wrapping multiple validation errors
// returned by TaskResult.ValidateAll() if the designated constraints aren't met.
type TaskResultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TaskResultMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TaskResultMultiError) AllErrors() []error { return m }

// TaskResultValidationError is the validation error returned by
// TaskResult.Validate if the designated constraints aren't met.
type TaskResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TaskResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TaskResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TaskResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TaskResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TaskResultValidationError) ErrorName() string { return "TaskResultValidationError" }

// Error satisfies the builtin error interface
func (e TaskResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTaskResult.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TaskResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TaskResultValidationError{}
